services:
  ratata:
    build: .
    container_name: ratata-web
    restart: unless-stopped
    ports:
      - "4003:4003"
    environment:
      - NODE_ENV=production
    env_file:
      - .env.production
